# Index Alignment (Ungraded) Exercises

**Note**: 

> This exercise has been written out in something called a Jupyter Notebook. We'll discuss Jupyter Notebooks in more detail later in this specialization—they are very a powerful tool for data science communication!—but for the time being, the notebook is just a convenient way for us to write out the exercise. You don't need to *do* anything with the notebook except read its contents—just use write your Python code in a regular `.py` file.

To illustrate how index alignment can sometimes lead to problems, let's consider the following example: suppose we're throwing a party, and we plan to give people prizes based on the order in which they arrive. The first person to arrive at the party will get 20 dollars, the second will get 10 dollars, and the third person doesn't get anything. 

To keep track of how many prizes everyone gets, we build a DataFrame with all the party attendees, their arrival order, and a column for keeping track of how much they've received in prizes. 

We can also build a Series with the prize amounts we plan to give people. 

### Exercise 1

Use the code below to get started: 

```python
import pandas as pd

attendees = pd.DataFrame(
    {
        "names": ["Jill", "Kumar", "Zaira"],
        "prizes": [0, 0, 0],
        "arrival_order": [2, 1, 3],
    }
)
arrival_prizes = pd.Series([20, 10, 0])
```

In [2]:
import pandas as pd

attendees =  pd.DataFrame(
    {
        "name": ["Jill", "Kumar", "Zaira"],
        "prizes": [0, 0, 0],
        "arrival_order": [2, 1, 3],
    }
)
arrival_prizes = pd.Series([20, 10, 0])

### Exercise 2

Now let's sort our `attendees` list by `arrival_order` so that the first row is the person who arrived first, the second is the person who arrived second, etc. to match how we've organized `arrival_prizes`.

In [12]:
attendees = attendees.sort_values('arrival_order')
attendees

    name  prizes  arrival_order
1  Kumar       0              1
0   Jill       0              2
2  Zaira       0              3

### Exercise 3

Now let's "give" everyone their arrival prizes by adding arrival prizes to people's prize column: 

```python
attendees["prizes"] = attendees["prizes"] + arrival_prizes
```

In [13]:
attendees["prizes"] = attendees["prizes"] + arrival_prizes
attendees

    name  prizes  arrival_order
1  Kumar      10              1
0   Jill      20              2
2  Zaira       0              3

### Exercise 4

Now let's look at the result. Does it look like what you expected? Do you know what went wrong?

After you've formulated your thoughts, open the `DO_NOT_OPEN_INITIALLY.ipynb` notebook next to this notebook.

R// There must be an error because the second guest received an expected prize that was even higher than the one awarded to the first attendee.

### Exercise 5

If you ever *want* to get alignment on row numbers, the easiest way to achieve that is to reset the indices on both objects you want to merge. When one re-sets indices without specifying a column to become the new index, the new index will just be row-numbers. 

So reset prizes to 0, do what you need to do to get the order right, reset the index, and try again.

In [17]:
attendees = pd.DataFrame(
    {
        "names": ["Jill", "Kumar", "Zaira"],
        "prizes": [0, 0, 0],
        "arrival_order": [2, 1, 3],
    }
)
arrival_prizes = pd.Series([20, 10, 0])

In [18]:
attendees = attendees.sort_values("arrival_order")
attendees

   names  prizes  arrival_order
1  Kumar       0              1
0   Jill       0              2
2  Zaira       0              3

In [19]:
attendees = attendees.reset_index()
attendees

   index  names  prizes  arrival_order
0      1  Kumar       0              1
1      0   Jill       0              2
2      2  Zaira       0              3

In [20]:
attendees["prizes"] = attendees["prizes"] + arrival_prizes
attendees

   index  names  prizes  arrival_order
0      1  Kumar      20              1
1      0   Jill      10              2
2      2  Zaira       0              3

**Note:** When you reset the index on a Series, the Series is converted to a DataFrame, and the old index is added as a column. To avoid this behavior and just drop the old index when re-setting indices (in either a Series or a DataFrame), use the `drop=True` argument when resetting the index.

### Exercise 6

OK, so besides doing automatic alignment, is there a reason to use indices?

Let's find out. Create the following fake dataset of social security numbers and some "names" (random strings). Warning: this will take a little time to run.  

```python
import numpy.random as npr
import string
import random

npr.seed(42)
random.seed(42)

size = 1000000  # 1,000,000
people = pd.DataFrame(
    {
        "social_security_numbers": npr.randint(low=10000000, high=99999999, size=size),
        "names": [
            "".join(random.choices(string.ascii_uppercase, k=10)) for i in range(size)
        ],
    }
)
```

In [68]:
import numpy.random as npr
import string
import random

npr.seed(42)
random.seed(42)

size = 1000000  # 1,000,000
people = pd.DataFrame(
    {
        "social_security_numbers": npr.randint(low=10000000, high=99999999, size=size),
        "names": [
            "".join(random.choices(string.ascii_uppercase, k=10)) for i in range(size)
        ],
    }
)

### Exercise 7

Now subset your data to get the social security number associated with the name of "TPKSMSLREI". (Yes, there are ways to get real random names, but they take a while to run because they query websites that generate fake names, so we're just doing this!).

In [59]:
people.head()

   social_security_numbers       names
0                 75682867  QAHFTRXCKA
1                 66755036  FNAFQOFPVA
2                 66882282  USIEYICCWP
3                 31081788  USNZJOVQWP
4                 23315092  SBFHCGCHQJ

In [44]:
def get_weird_row():
    return people.loc[people["names"] == "TPKSMSLREI", "social_security_numbers"]

In [45]:
get_weird_row()

299029    84423764
Name: social_security_numbers, dtype: int32

### Exercise 8

Now time your operation using the `timeit` function in the `timeit` library. Just wrap your operation in a function (call it `get_weird_row()`), then run:

```python
import timeit

timeit.timeit(get_weird_row, number=100)
```

Note the lack of parentheses when passing your function to `timeit.timeit`. The `number=100` just tells `timeit` to run your function 100 times, then average the run time over those 100 runs.

In [47]:
import timeit

timeit.timeit(get_weird_row, number=100)

0.8894731999607757

### Exercise 9

Now make `names` your index for this data. Then try subsetting using `loc[]` to get all the observations with the name of "TPKSMSLREI" and time the operation. How do your run times compare?

In [79]:
get_weird_row_indexed = people.set_index("names")
get_weird_row_indexed.head()

            social_security_numbers
names
QAHFTRXCKA                 75682867
FNAFQOFPVA                 66755036
USIEYICCWP                 66882282
USNZJOVQWP                 31081788
SBFHCGCHQJ                 23315092

In [81]:
def time_indexed_search():
    return get_weird_row_indexed.loc["TPKSMSLREI"]

In [82]:
timeit.timeit(time_indexed_search, number=1000)

0.03932600002735853

R// Subsetting a dataframe using indices is generally more efficient than conventional queries.

## Take-away

So in short: indices can be nice in that they do automatic alignment, provided you're expecting it. Moreover, if you want to pull random rows out of your dataset, it is often much faster than a regular query!